const departmentSeed = [
  {
    name: 'Cardiology',
    slug: 'cardiology',
    tagline: 'Heart and vascular care with rapid diagnostics',
    description:
      'Comprehensive cardiac evaluations, preventive screenings, interventional planning, and long-term recovery support.',
    icon: 'HeartPulse',
    averageWaitTime: '10 min average triage time',
    consultationFee: 'From Rs. 900',
    availability: 'Daily, 8:00 AM to 6:00 PM',
    keyServices: ['ECG and echo review', 'Heart failure management', 'Preventive screening'],
    spotlightMetric: '96% treatment adherence support rate',
  },
  {
    name: 'Neurology',
    slug: 'neurology',
    tagline: 'Advanced brain, spine, and nerve consultations',
    description:
      'Specialist-led care for migraines, seizure management, stroke recovery pathways, and neuro-diagnostic follow-up.',
    icon: 'Brain',
    averageWaitTime: '12 min average specialist queue',
    consultationFee: 'From Rs. 1100',
    availability: 'Mon to Sat, 9:00 AM to 5:30 PM',
    keyServices: ['Stroke risk review', 'Epilepsy management', 'Neuro rehabilitation planning'],
    spotlightMetric: 'Dedicated stroke coordination desk',
  },
  {
    name: 'Orthopedics',
    slug: 'orthopedics',
    tagline: 'Bone, joint, spine, and mobility restoration',
    description:
      'Integrated fracture care, sports injury review, chronic pain planning, and post-surgery recovery support.',
    icon: 'Bone',
    averageWaitTime: '15 min average consult start',
    consultationFee: 'From Rs. 850',
    availability: 'Daily, 8:30 AM to 7:00 PM',
    keyServices: ['Arthritis care', 'Sports injury assessment', 'Joint recovery programs'],
    spotlightMetric: 'On-site rehab coordination for follow-ups',
  },
  {
    name: 'Pulmonology',
    slug: 'pulmonology',
    tagline: 'Respiratory care for acute and chronic conditions',
    description:
      'Care pathways for asthma, COPD, sleep-related breathing issues, infection recovery, and lung function monitoring.',
    icon: 'Lungs',
    averageWaitTime: '8 min respiratory nurse triage',
    consultationFee: 'From Rs. 950',
    availability: 'Mon to Sun, 7:30 AM to 7:00 PM',
    keyServices: ['Asthma review', 'Sleep breathing consults', 'Pulmonary function screening'],
    spotlightMetric: 'Same-week respiratory follow-up slots',
  },
  {
    name: 'Pediatrics',
    slug: 'pediatrics',
    tagline: 'Gentle, family-centered care for children',
    description:
      'Routine pediatric checkups, developmental guidance, vaccination planning, and rapid consultation support for children.',
    icon: 'Baby',
    averageWaitTime: 'Family priority scheduling available',
    consultationFee: 'From Rs. 700',
    availability: 'Daily, 9:00 AM to 8:00 PM',
    keyServices: ['Child wellness visits', 'Growth monitoring', 'Vaccination planning'],
    spotlightMetric: 'Dedicated child-friendly consultation suites',
  },
  {
    name: 'Preventive Care',
    slug: 'preventive-care',
    tagline: 'Checkups and health planning before issues escalate',
    description:
      'Executive health packages, lifestyle counseling, chronic risk assessment, and personalized annual care planning.',
    icon: 'ShieldCheck',
    averageWaitTime: 'Pre-booked wellness slots',
    consultationFee: 'Customized package pricing',
    availability: 'Mon to Fri, 7:00 AM to 4:00 PM',
    keyServices: ['Annual screenings', 'Lifestyle medicine review', 'Corporate wellness support'],
    spotlightMetric: 'Integrated checkup reporting in one visit',
  },
];

const doctorSeed = [
  {
    name: 'Dr. Aarya Menon',
    slug: 'dr-aarya-menon',
    department: 'Cardiology',
    specialty: 'Interventional Cardiology',
    credentials: 'MD, DM Cardiology',
    bio: 'Focuses on early intervention, heart failure continuity planning, and patient education after acute cardiac episodes.',
    experienceYears: 14,
    rating: 4.9,
    reviewCount: 186,
    languages: ['English', 'Hindi', 'Tamil'],
    availability: ['Mon 9:00 AM to 1:00 PM', 'Wed 2:00 PM to 6:00 PM', 'Fri 9:00 AM to 1:00 PM'],
    focusAreas: ['Angioplasty follow-up', 'Chest pain screening', 'Heart health prevention'],
    education: ['Madras Medical College', 'AIIMS New Delhi'],
    avatarColor: '#1c6e74',
    featured: true,
  },
  {
    name: 'Dr. Kavin Rao',
    slug: 'dr-kavin-rao',
    department: 'Neurology',
    specialty: 'Clinical Neurology',
    credentials: 'MD, DM Neurology',
    bio: 'Supports patients with neurological disorders through structured diagnostics, family counseling, and recovery tracking.',
    experienceYears: 11,
    rating: 4.8,
    reviewCount: 149,
    languages: ['English', 'Kannada', 'Tamil'],
    availability: ['Tue 10:00 AM to 2:00 PM', 'Thu 1:00 PM to 5:00 PM', 'Sat 9:00 AM to 1:00 PM'],
    focusAreas: ['Migraine care', 'Seizure evaluation', 'Stroke rehabilitation'],
    education: ['JIPMER', 'NIMHANS'],
    avatarColor: '#2a4d8f',
    featured: true,
  },
  {
    name: 'Dr. Samaira Joshi',
    slug: 'dr-samaira-joshi',
    department: 'Orthopedics',
    specialty: 'Joint Preservation and Sports Injury',
    credentials: 'MS Orthopedics',
    bio: 'Works with patients on pain reduction, injury recovery, mobility restoration, and long-term strengthening plans.',
    experienceYears: 10,
    rating: 4.8,
    reviewCount: 132,
    languages: ['English', 'Marathi', 'Hindi'],
    availability: ['Mon 3:00 PM to 7:00 PM', 'Thu 9:00 AM to 1:00 PM', 'Sat 2:00 PM to 6:00 PM'],
    focusAreas: ['Sports injuries', 'Arthritis management', 'Post-op recovery'],
    education: ['Grant Medical College', 'KEM Hospital'],
    avatarColor: '#3a7d6f',
    featured: true,
  },
  {
    name: 'Dr. Rehan Siddiqui',
    slug: 'dr-rehan-siddiqui',
    department: 'Pulmonology',
    specialty: 'Pulmonary and Sleep Medicine',
    credentials: 'MD Pulmonary Medicine',
    bio: 'Treats respiratory conditions with an emphasis on long-term breathing improvement and evidence-based follow-up.',
    experienceYears: 13,
    rating: 4.7,
    reviewCount: 118,
    languages: ['English', 'Hindi', 'Urdu'],
    availability: ['Daily 8:00 AM to 12:00 PM'],
    focusAreas: ['Asthma control', 'COPD review', 'Sleep-related breathing concerns'],
    education: ['St. Johns Medical College', 'CMC Vellore'],
    avatarColor: '#537895',
    featured: true,
  },
  {
    name: 'Dr. Ira Nandakumar',
    slug: 'dr-ira-nandakumar',
    department: 'Pediatrics',
    specialty: 'General Pediatrics',
    credentials: 'MD Pediatrics',
    bio: 'Known for calm consultations, child-friendly communication, and practical guidance for parents during treatment.',
    experienceYears: 9,
    rating: 4.9,
    reviewCount: 203,
    languages: ['English', 'Malayalam', 'Tamil'],
    availability: ['Mon to Fri 11:00 AM to 5:00 PM', 'Sun 10:00 AM to 1:00 PM'],
    focusAreas: ['Child wellness', 'Vaccination counseling', 'Fever and infection review'],
    education: ['Government Medical College Kozhikode', 'Apollo Hospitals'],
    avatarColor: '#1f8a70',
    featured: true,
  },
  {
    name: 'Dr. Vivaan Chatterjee',
    slug: 'dr-vivaan-chatterjee',
    department: 'Preventive Care',
    specialty: 'Preventive and Lifestyle Medicine',
    credentials: 'MD Internal Medicine',
    bio: 'Helps patients lower long-term health risks through preventive screening, habit change planning, and data-led care reviews.',
    experienceYears: 15,
    rating: 4.8,
    reviewCount: 161,
    languages: ['English', 'Hindi', 'Bengali'],
    availability: ['Tue to Sat 7:30 AM to 2:00 PM'],
    focusAreas: ['Executive checkups', 'Metabolic risk review', 'Lifestyle medicine'],
    education: ['Calcutta National Medical College', 'PGIMER Chandigarh'],
    avatarColor: '#245c73',
    featured: false,
  },
];

module.exports = {
  departmentSeed,
  doctorSeed,
};
