services:
  - type: web
    name: carevista-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SEED_ON_START
        value: false
