export const fallbackDepartments = [
  {
    _id: 'fallback-dept-cardiology',
    name: 'Cardiology',
    icon: 'CV',
    description:
      'CareVista Cardiology provides preventive heart screenings, advanced diagnostics, interventional support, and long-term cardiac rehabilitation plans for adults of all ages.',
    shortDescription:
      'Comprehensive heart and vascular care with preventive and acute services.',
    services: [
      'Heart health screenings',
      'Electrocardiograms',
      'Echocardiography',
      'Hypertension management',
    ],
    headDoctor: 'Dr. Sarah Mitchell',
    available: true,
  },
  {
    _id: 'fallback-dept-neurology',
    name: 'Neurology',
    icon: 'NR',
    description:
      'Our Neurology department evaluates headaches, seizures, stroke risk, memory concerns, and complex nerve disorders through coordinated diagnostic and follow-up care.',
    shortDescription:
      'Specialist care for the brain, spine, nerves, and stroke recovery.',
    services: [
      'Migraine assessment',
      'Stroke prevention',
      'Nerve conduction studies',
      'Epilepsy management',
    ],
    headDoctor: 'Dr. James Okafor',
    available: true,
  },
  {
    _id: 'fallback-dept-orthopedics',
    name: 'Orthopedics',
    icon: 'OR',
    description:
      'Orthopedics at CareVista supports joint preservation, fracture recovery, sports injuries, and mobility restoration with a strong focus on rehabilitation and long-term strength.',
    shortDescription:
      'Bone, joint, and mobility care for injuries and chronic pain.',
    services: [
      'Fracture care',
      'Joint pain treatment',
      'Sports injury recovery',
      'Rehabilitation planning',
    ],
    headDoctor: 'Dr. Priya Sharma',
    available: true,
  },
  {
    _id: 'fallback-dept-pediatrics',
    name: 'Pediatrics',
    icon: 'PD',
    description:
      'The Pediatrics team delivers family-centered care for newborns, children, and adolescents, including routine wellness checks, developmental reviews, and acute illness evaluation.',
    shortDescription:
      'Compassionate pediatric care from infancy through adolescence.',
    services: [
      'Well-child visits',
      'Vaccination guidance',
      'Growth monitoring',
      'Acute pediatric consultations',
    ],
    headDoctor: 'Dr. Carlos Reyes',
    available: true,
  },
  {
    _id: 'fallback-dept-oncology',
    name: 'Oncology',
    icon: 'ON',
    description:
      'CareVista Oncology coordinates diagnosis, treatment planning, infusion services, survivorship support, and compassionate navigation for patients and caregivers through each phase of care.',
    shortDescription:
      'Integrated cancer diagnosis, treatment planning, and support services.',
    services: [
      'Cancer screening reviews',
      'Treatment planning',
      'Infusion coordination',
      'Supportive care',
    ],
    headDoctor: 'Dr. Emily Chen',
    available: true,
  },
  {
    _id: 'fallback-dept-emergency',
    name: 'Emergency Medicine',
    icon: 'ER',
    description:
      'Emergency Medicine operates around the clock with rapid triage, stabilization, trauma evaluation, and coordination with specialty teams for urgent and life-threatening conditions.',
    shortDescription:
      '24/7 emergency evaluation, stabilization, and urgent care routing.',
    services: [
      '24/7 triage',
      'Trauma stabilization',
      'Critical care coordination',
      'Rapid diagnostics',
    ],
    headDoctor: 'Dr. Marcus Webb',
    available: true,
  },
];

export const fallbackDoctors = [
  {
    _id: 'fallback-doc-sarah-mitchell',
    name: 'Dr. Sarah Mitchell',
    specialty: 'Interventional Cardiology',
    department: 'Cardiology',
    imageUrl: '',
    bio: 'Dr. Mitchell leads the Cardiology service with a strong focus on prevention, early intervention, and recovery planning for patients living with complex cardiovascular conditions.',
    experience: 18,
    languages: ['English', 'Spanish'],
    available: true,
    rating: 4.9,
    reviewCount: 214,
  },
  {
    _id: 'fallback-doc-james-okafor',
    name: 'Dr. James Okafor',
    specialty: 'Clinical Neurology',
    department: 'Neurology',
    imageUrl: '',
    bio: 'Dr. Okafor is known for clear neurological evaluations, thoughtful diagnostic planning, and careful communication with patients managing chronic neurological symptoms.',
    experience: 16,
    languages: ['English', 'French'],
    available: true,
    rating: 4.8,
    reviewCount: 186,
  },
  {
    _id: 'fallback-doc-priya-sharma',
    name: 'Dr. Priya Sharma',
    specialty: 'Orthopedic Surgery',
    department: 'Orthopedics',
    imageUrl: '',
    bio: 'Dr. Sharma combines surgical precision with rehabilitation-first planning, helping patients recover strength, confidence, and long-term mobility after injury or chronic pain.',
    experience: 14,
    languages: ['English', 'Hindi', 'Punjabi'],
    available: true,
    rating: 4.9,
    reviewCount: 201,
  },
  {
    _id: 'fallback-doc-carlos-reyes',
    name: 'Dr. Carlos Reyes',
    specialty: 'General Pediatrics',
    department: 'Pediatrics',
    imageUrl: '',
    bio: 'Dr. Reyes provides calm, family-centered pediatric care with particular strength in preventive visits, developmental milestones, and acute same-day child consultations.',
    experience: 13,
    languages: ['English', 'Spanish'],
    available: true,
    rating: 4.8,
    reviewCount: 233,
  },
  {
    _id: 'fallback-doc-emily-chen',
    name: 'Dr. Emily Chen',
    specialty: 'Medical Oncology',
    department: 'Oncology',
    imageUrl: '',
    bio: 'Dr. Chen leads the Oncology department with an emphasis on multidisciplinary planning, compassionate patient education, and continuity through treatment and survivorship.',
    experience: 17,
    languages: ['English', 'Mandarin'],
    available: true,
    rating: 5,
    reviewCount: 167,
  },
  {
    _id: 'fallback-doc-marcus-webb',
    name: 'Dr. Marcus Webb',
    specialty: 'Emergency Medicine',
    department: 'Emergency Medicine',
    imageUrl: '',
    bio: 'Dr. Webb oversees rapid triage and emergency stabilization with a disciplined, team-based approach that keeps urgent patients moving quickly toward the right level of care.',
    experience: 15,
    languages: ['English'],
    available: true,
    rating: 4.7,
    reviewCount: 145,
  },
];
